### ISSUE TITLE
what if we add '120ml' Orange and '40ml' Wodka?

### ISSUE THREAD

**Issue by Jogenist** [Jogenist/CM-IoT-App-Bestellstation#5]
right now the code is just adding up all values of the ingredients.
But sometimes this can be inconsistent and can be a problem for the machine while interpreting these numbers.
Example:
1. if there is no ingredient added the numbers are:        00000000 (eight zeros for eight ingredients)
2. if we add '20ml' Wodka, the numbers are:                  200000000 (20 plus seven zeros)
3. if we add '120ml' Orange, the numbers are:               20120000000 (20 plus 120 plus six zeros)
Problem:
- it is not possible to tell if we have '20ml' Wodka and '120ml' Orange, or if we have '201ml' of Wodka and '20ml' of Orange (bad example)
- this error adds up with more ingredients, so it is not 100% defined in these numbers what we have ordered

**Comment by Gremple** [comment]
The problem was solved by agreeing on string syntax. The syntax says that each ingredient is limited to a character length of three and initialized with zeros. The following changes have been made:

1. An extra string was created for each ingredient.
2. As soon as the quantity of an ingredient is changed, the function 'generateString(...)' is called which simultaneously changes the string and takes care of the character length. The function returns a string.
3. The function 'generateString' is called when decrementing and incrementing the ingredients and at the end a string is calculated from all ingredients, which is described on the glass when the order is completed.
